* Papier Theme
[[https://github.com/zovt/papier-gtk-theme][Papier]] is a modification of the [[http://snwh.org/paper/][Paper]] theme originally developed by snwh. Papier seeks to be a lighter, more colourful theme.

** Preamble
While the original theme is focused on providing assets and files for a bunch of major desktop environments, this theme is focused on GNOME 3.16 and onwards.

This theme is meant to be brighter and more colourful than the original Paper theme. It is almost a mix of Phosphene and Paper
*** Using the Source
Necessities to edit the assets:

 * inkscape
 * python3

To render new assets from their source SVG files, run the following:

#+BEGIN_SRC sh
  ./render-assets.sh
#+END_SRC

Note that these are not my scripts and I have no idea how they work :)

If scripts are throwing errors, they may not be executable, try:
	
	chmod +x *

Each script will look in the asset source directories (../src/*) and render the respective assets (provided there are changes) to the appropriate locations.
